/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class firewall_NativeBridge */

#ifndef _Included_firewall_NativeBridge
#define _Included_firewall_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     firewall_NativeBridge
 * Method:    startFirewall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_firewall_NativeBridge_startFirewall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
